/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rest.assured.exemple;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.*;

public class AppTest {

    @BeforeClass
    public static void setup() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        baseURI = "https://reqres.in";
        basePath = "/api";
    }

    @Test
    public void listUserWithStatusOK() {
        given().
                params("page", 2).
        when().
                get("/users").
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test
    public void createUserWithStatusCREATED() {
        given().
                contentType(ContentType.JSON).
                body("{\n" +
                        "    \"name\": \"Dionata\",\n" +
                        "    \"job\": \"Developer\"\n" +
                        "}").
        when().
                post("/users")
        .then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("Dionata"));
    }
}
